- components/Bridge/MintAndRedeem/shared/Deposit/index.tsx
- store/slices/bridges/selectors.ts
1. Remove actionsParams in funkit checkout
2. Switch to a pure buy flow on the source asset only if user has insufficient balance
> feat: switch off userOp

- package-lock.json
- package.json
Reference: https://github.com/Ion-Protocol/nucleus-app/pull/9
> Update funkit to 2.0.11

- components/shared/RewardsAndPoints/RewardsTooltipContent/connector.ts
- store/slices/bridges/calculateApy.ts
- store/slices/bridges/selectors.ts
- Before, if the APY was 1000%, it was being shown as 10%.
> APY as Percentage Values

- components/Bridge/BridgeTitle/Tvl/index.tsx
- components/Bridge/MintAndRedeem/shared/TokenDestination/connector.ts
- store/slices/balance/selectors.ts
- store/slices/bridges/selectors.ts
- store/slices/bridges/thunks.ts
- utils/bigint.ts
- utils/misc.ts
- utils/number.ts
Abbreviates large TVL numbers.
> Abbreviate TVL

- api/contracts/Accountant/accountantState.ts
- api/contracts/Accountant/index.ts
- config/networks.ts
- contracts/AccountantWithRateProviders.json
- middleware.ts
- pages/tokens/[tokens]/index.tsx
- store/hooks/useStoreInitializer.ts
- store/slices/networkAssets/extraReducers.ts
- store/slices/networkAssets/initialState.ts
- store/slices/networkAssets/selectors.ts
- store/slices/networkAssets/thunks.ts
- types/Chain.ts
Automatically detects when a network asset is paused from the contracts and show the under maintenance page.
> Automatically detect when page is paused

- store/slices/userProofSlice/selectors.ts
> staging -> main

- components/NetworkAsset/MintAndRedeem/shared/Summary/connector.ts
- components/NetworkAsset/MintAndRedeem/shared/Summary/index.tsx
updated exchange rate to display source token name instead of hard-coded value
> fix(mint-summary): 

- hooks/useRedeem.tsx
updated logic for approve token, added logs to debug staging
> fix(useRedeem): 

- store/slices/networkAssets/thunks.ts
fixed double concatenation of sei /tx/tx/ on explorer URL
> fix(Sei-Tx-explorer-url):

- config/networks.ts
> fix(sseth-fee):

- components/shared/RewardsAndPoints/RewardsTooltipContent/index.tsx
- pages/tokens/[tokens]/index.tsx
- Remove Token Incentives Section (Default Yield and Rewards section is left untouched)
- Remove the "Check back soon" message
- Revert to original state
- The Rewards & History section should still work as expected.
> Remove old incentives information

- components/NavDrawer/index.tsx
- components/orders-table.tsx
- components/table/multi-select-filter.tsx
- components/table/table-body.tsx
- pages/withdrawals/index.tsx
- styles/theme/componentStyles/index.ts
update page name and link from withdrawl to withdrawals. 
added refetch on mount or arg change to withdrawal order query
> fix(Page-Name): 

- .github/ISSUE_TEMPLATE/new-ticket-template.md
- .github/ISSUE_TEMPLATE/task.md
- config/networks.ts
- store/slices/networkAssets/selectors.ts
- types/Chain.ts
fix(networks.ts,-networkAssets/selectors.ts): 
update to allow fees to be associated with the selected want asset
> Handle withdrawal fee on per want asset basis

- config/networks.ts
updated withdrawal want assets array
> fix(NetworkAssets): 

- config/networks.ts
add weth on rari to token config
add rari as allowed destination chain
test tx: https://mainnet.explorer.rarichain.org/tx/0xbb141d865bc92dbe5fd53b24691a4b8c7aab6ffbf394b704222cb8f77b78cd72
> fix(networks): add rari as destination chain

- config/networks.ts
> fix(fETH-Bridge): 

- config/networks.ts
update deposit source to only be ethereum main net. 
updated withdraw destination to only be ethereum
> fix(Boba-Deposit-and-Withdrawal): 

- config/tokens.ts
- store/slices/balance/thunks.ts
- store/slices/networkAssets/selectors.ts
- store/slices/networkAssets/thunks.ts
Fixed weth balance not showing on Form. Related to tickets 971 and 980 on discord.
> fix weth balance

- config/networks.ts
- store/slices/networkAssets/thunks.ts
- types/Chain.ts
updated network.ts to contain additional tvl sources object allowing for my accurate tvl calculations
> fix(config/networks.ts): 

- config/networks.ts
updated config in accordance with the vault depreciation strategy
> fix(fix/vault-deprecation-strategy): 
